### ISSUE TITLE
error 4000: Instance of library class [RegisterFilterLib] is not found

### ISSUE THREAD

**Issue by mouseos** [edk2-porting/edk2-rk3399#6]
I ran  `bash build.sh --device polaris` . But I can't compile. Because of error 4000.

```shell
Ran 302 tests in 4.457s

OK
make[1]: ディレクトリ '/media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2/BaseTools/Tests' から出ます
make: ディレクトリ '/media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2/BaseTools' から出ます
+ rm -f boot_polaris.img uefi_img
+ rm -f workspace/Build/sdm845Pkg/DEBUG_GCC5/FV/SDM845PKG_UEFI.fd
+ GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
+ build -s -n 0 -a AARCH64 -t GCC5 -p sdm845Pkg/polaris.dsc -b DEBUG
Build environment: Linux-5.15.0-67-generic-x86_64-with-glibc2.29
Build start time: 22:46:37, Mar.23 2023

WORKSPACE        = /media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2-rk3399/workspace
PACKAGES_PATH    = /media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2:/media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2-platforms:/media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2-rk3399
EDK_TOOLS_PATH   = /media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2/BaseTools
CONF_PATH        = /media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2/Conf
PYTHON_COMMAND   = /usr/bin/python3.8


Processing meta-data 
.Architecture(s)  = AARCH64
Build target     = DEBUG
Toolchain        = GCC5

Active Platform          = /media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2-rk3399/sdm845Pkg/polaris.dsc


build.py...
/media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2-rk3399/sdm845Pkg/polaris.dsc(...): error 4000: Instance of library class [RegisterFilterLib] is not found
	in [/media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic.inf] [AARCH64]
	consumed by module [/media/yuuma/Expansion/work/android/rockchip/rk3399/zmooth/firmware/uefi/edk2/workspace-edk2/edk2/ArmPlatformPkg/PrePi/PeiUniCore.inf]
 

- Failed -
Build end time: 22:46:38, Mar.23 2023
Build total time: 00:00:01
```

**Comment by mouseos** [comment]
Cannot compile even if I follow the readme.
Even if I use the past edk2 source code, etc., I get the same error and cannot compile.
Please teach me how to compile it.

**Comment by mouseos** [comment]
I got this result when I use this.
 `git clone https://github.com/tianocore/edk2.git -b edk2-stable201911 --recursive --depth=1`
 
```bash
Ran 280 tests in 0.836s

OK
make[1]: ディレクトリ '/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Tests' から出ます
make: ディレクトリ '/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools' から出ます
+ rm -f boot_polaris.img uefi_img
+ rm -f workspace/Build/sdm845Pkg/DEBUG_GCC5/FV/SDM845PKG_UEFI.fd
+ GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
+ build -s -n 0 -a AARCH64 -t GCC5 -p sdm845Pkg/polaris.dsc -b DEBUG
Build environment: Linux-5.15.0-86-generic-x86_64-with-glibc2.29
Build start time: 11:30:53, Oct.23 2023

WORKSPACE        = /home/yuuma/work/android/zmooth/workspace-edk2/edk2-rk3399/workspace
PACKAGES_PATH    = /home/yuuma/work/android/zmooth/workspace-edk2/edk2:/home/yuuma/work/android/zmooth/workspace-edk2/edk2-platforms:/home/yuuma/work/android/zmooth/workspace-edk2/edk2-rk3399
EDK_TOOLS_PATH   = /home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools
CONF_PATH        = /home/yuuma/work/android/zmooth/workspace-edk2/edk2/Conf
PYTHON_COMMAND   = /usr/bin/python3.8


Processing meta-data .
Architecture(s)  = AARCH64
Build target     = DEBUG
Toolchain        = GCC5

Active Platform          = /home/yuuma/work/android/zmooth/workspace-edk2/edk2-rk3399/sdm845Pkg/polaris.dsc
...build: : warning: Module MetaFile [Sources] is missing local header!
    Local Header: /home/yuuma/work/android/zmooth/workspace-edk2/edk2-rk3399/sdm845pkg/sdm845dxe/sdm845dxe.h not found in /home/yuuma/work/android/zmooth/workspace-edk2/edk2-rk3399/sdm845Pkg/sdm845Dxe/sdm845Dxe.inf
build: : warning: Module MetaFile [Sources] is missing local header!
    Local Header: /home/yuuma/work/android/zmooth/workspace-edk2/edk2/embeddedpkg/application/androidfastboot/androidfastbootapp.h not found in /home/yuuma/work/android/zmooth/workspace-edk2/edk2/EmbeddedPkg/Application/AndroidFastboot/AndroidFastbootApp.inf
build: : warning: Module MetaFile [Sources] is missing local header!
    Local Header: /home/yuuma/work/android/zmooth/workspace-edk2/edk2/embeddedpkg/drivers/virtualkeyboarddxe/virtualkeyboard.h not found in /home/yuuma/work/android/zmooth/workspace-edk2/edk2/EmbeddedPkg/Drivers/VirtualKeyboardDxe/VirtualKeyboardDxe.inf
Traceback (most recent call last):
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/AutoGen/AutoGenWorker.py", line 244, in run
    Ma.CreateCodeFile(False)
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/AutoGen/ModuleAutoGen.py", line 1867, in CreateCodeFile
    for File in self.AutoGenFileList:
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/Common/caching.py", line 28, in __get__
    Value = obj.__dict__[self._function.__name__] = self._function(obj)
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/AutoGen/ModuleAutoGen.py", line 980, in AutoGenFileList
    GenC.CreateCode(self, AutoGenC, AutoGenH, StringH, AutoGenUniIdf, UniStringBinBuffer, StringIdf, AutoGenUniIdf, IdfGenBinBuffer)
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/AutoGen/GenC.py", line 2032, in CreateCode
    CreateProtocolDefinitionCode(Info, AutoGenC, AutoGenH)
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/AutoGen/GenC.py", line 1582, in CreateProtocolDefinitionCode
    if Info.ProtocolList:
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/Common/caching.py", line 28, in __get__
    Value = obj.__dict__[self._function.__name__] = self._function(obj)
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/AutoGen/ModuleAutoGen.py", line 1091, in ProtocolList
    RetVal = OrderedDict(self.Module.Protocols)
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/Common/caching.py", line 28, in __get__
    Value = obj.__dict__[self._function.__name__] = self._function(obj)
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/Workspace/InfBuildData.py", line 604, in Protocols
    EdkLogger.error('build', RESOURCE_NOT_AVAILABLE,
  File "/home/yuuma/work/android/zmooth/workspace-edk2/edk2/BaseTools/Source/Python/Common/EdkLogger.py", line 284, in error
    raise FatalError(ErrorCode)
Common.BuildToolError.FatalError: 16384


build.py...
/home/yuuma/work/android/zmooth/workspace-edk2/edk2-rk3399/sdm845Pkg/Drivers/MmcDxe/MmcDxe.inf(-1): error 4000: Value of Protocol [gEmbeddedMmcHostProtocolGuid] is not found under [Protocols] section in
	/home/yuuma/work/android/zmooth/workspace-edk2/edk2/EmbeddedPkg/EmbeddedPkg.dec
	/home/yuuma/work/android/zmooth/workspace-edk2/edk2/MdePkg/MdePkg.dec
 

- Done -
Build end time: 11:30:57, Oct.23 2023
Build total time: 00:00:04

+ echo 'Build done. check workspace/Build/sdm845Pkg/DEBUG_GCC5/FV/SDM845PKG_UEFI.fd Use it as a Linux kernel'
Build done. check workspace/Build/sdm845Pkg/DEBUG_GCC5/FV/SDM845PKG_UEFI.fd Use it as a Linux kernel

```
